name: Magisk Build

on:
  push:
    branches: [master]
    paths:
      - "app/**"
      - "native/**"
      - "buildSrc/**"
      - "build.py"
      - "gradle.properties"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build Magisk artifacts
    runs-on: macos-14
    strategy:
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          is-asset-build: true

      - name: Build resetprop
        run: ./build.py -vr native resetprop

      - name: Stop gradle daemon
        run: ./gradlew --stop

      - name: Find path
        run: find $(pwd) -type f -name "resetprop"
          
      - name: Upload arm libs
        uses: actions/upload-artifact@v4
        with: 
          name: libresetprop-arm32
          path: /Users/runner/work/Magisk/Magisk/native/out/armeabi-v7a/*
          
      - name: Upload arm64 libs
        uses: actions/upload-artifact@v4
        with: 
          name: libresetprop-arm64
          path: /Users/runner/work/Magisk/Magisk/native/out/arm64-v8a/*
          
      - name: Upload x86_64 libs
        uses: actions/upload-artifact@v4
        with: 
          name: libresetprop-x86_64
          path: /Users/runner/work/Magisk/Magisk/native/out/x86_64/*
